// event listener constants
const EVENTS = {
    GAME_STATE: "game_state"
}

// game life cycle states
const GAME_LIFECYCLE_STATE = {
    DOTA_GAMERULES_STATE_INIT: "DOTA_GAMERULES_STATE_INIT",
    DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD: "DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD",
    DOTA_GAMERULES_STATE_STRATEGY_TIME: "DOTA_GAMERULES_STATE_STRATEGY_TIME",
    DOTA_GAMERULES_STATE_TEAM_SHOWCASE: "DOTA_GAMERULES_STATE_TEAM_SHOWCASE",
    DOTA_GAMERULES_STATE_PRE_GAME: "DOTA_GAMERULES_STATE_PRE_GAME",
    DOTA_GAMERULES_STATE_GAME_IN_PROGRESS: "DOTA_GAMERULES_STATE_GAME_IN_PROGRESS",
    DOTA_GAMERULES_STATE_POST_GAME: "DOTA_GAMERULES_STATE_POST_GAME"
}